baseURL = 'https://londonco2storage.github.io/'
languageCode = 'en-us'
title = 'The London Register of Subsurface CO2 Storage'

[menus]

[[menus.main]]
name = 'The London Register of Subsurface CO<sub>2</sub> Storage'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'About the Project'
pageRef = '/project'
weight = 20

[[menus.main]]
name = 'Additional visualisation'
pageRef = '/visualisation'
weight = 30

# [[menus.main]]
# name = 'Report'
# pageRef = '/report'
# weight = 40
