baseURL = 'https://imperialcollegelondon.github.io/The-London-Register-of-Subsurface-CO2-Storage/'
languageCode = 'en-us'
title = 'The London Register of Subsurface CO2 Storage'

[menus]

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Data &amp; Downloads'
pageRef = '/data'
weight = 20

[[menus.main]]
name = 'News'
pageRef = '/news'
weight = 25

[[menus.main]]
name = 'Additional visualisation'
pageRef = '/visualisation'
weight = 30

[[menus.main]]
name = 'About'
pageRef = '/project'
weight = 40
